builders:
  animatedWidgetBuilder:
    import: 'package:animated_widget_generator/animated_widget_generator.dart'
    builder_factories: ['animatedWidgetBuilder']
    auto_apply: dependents
    build_extensions: {".dart":[".animatable_widget.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
