name: animated_widget_generator
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  path: ^1.8.0
  source_gen: ^1.0.2
  animated_widget_annotations:
    path: ../animated_widget_annotations

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: ^2.0.4
